name: build

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
      - release
  workflow_dispatch:
    inputs:
      update:
        description: 'build to update'
        required: true
        default: 'Build'

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'version:') || contains(github.event.head_commit.message, '[deploy]') }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up node 14.x
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Build distributable
      run: |
        npm ci
        ls -al
        npm run build

    - name: Commit report
      run: |
          git config user.name 'Github Actions'
          git config user.email 'joo-na@users.noreply.github.com'
          git add -fN dist
          git diff -- dist > git.diff
          [ -s git.diff ] && git add -f dist && git commit -m ":rocket: deploy at `date "+%Y-%m-%d %H:%M"`" && git push || echo "Skip commit"
